### ISSUE TITLE
NameError: name 'exp_mat' is not defined

### ISSUE THREAD

**Issue by CFVALLS** [douglasyao/FR-Perturb#6]
It seems that if you run_FR_Perturb.py  with control-perturbation-name , but args.covariates = None 

Example 

```
# Execute the script with the correct inputs
python3 run_FR_Perturb.py --input-h5ad "$INPUT_H5AD" \
--input-perturbation-matrix "$INPUT_PERTURBATION_MATRIX" \
--control-perturbation-name OR4D2,OR11H1,OR13C4,OR10H2,OR11H4,OR9Q1,OR4M2,OR13C7,OR13H1,OR10J3,NEGATIVE_CONTROL \
--compute-pval \
--out test
```

There error arises:
NameError: name 'exp_mat' is not defined

Traceback (most recent call last):
  File "run_FR_Perturb.py", line 266, in <module>
    ctrl_exp = exp_mat[ctrl_idx,:].mean(axis=0)
NameError: name 'exp_mat' is not defined

this is because: 
exp_mat is define in here (line 248) :
```
# Normalize matrix
if cov_mat is not None:
    log.info('Regressing out covariates...  ')
     exp_mat = regress_covariates(dat.X, cov_mat)
```

**Comment by alvaradocx** [comment]
I've run into the same issue as well. Have you been able to resolve the issue?

**Comment by CFVALLS** [comment]
> I've run into the same issue as well. Have you been able to resolve the issue?


Yes i fork it and then defined the variable outside of the if statement. 
But i started using covariates - so i didnt come across with that problem anymore (if i remember correctly)

**Comment by douglasyao** [comment]
Very sorry for the extremely late response. The issue should be fixed now. Thanks.
